In [6]:
import numpy as np

In [9]:
np.load('/home/jongchan/SDIRL/results/TD3_Hopper-v2_0_exp1_d_704_08.npy')

array([  18.0233928 ,   18.0233928 ,   18.0233928 ,   18.0233928 ,
         18.0233928 ,   18.0233928 ,  234.23317754,  245.7702487 ,
        317.80978509,  442.69448303, 1045.53676009,  380.15377064,
        546.80412451, 1089.01469767, 1059.24104927, 1034.76922779,
       1052.89475796, 1023.99808035, 1010.97566358, 1047.24360166,
       1042.89960985,  687.64731912,  646.1781151 , 1050.04611276,
       1041.67110116, 1038.23830693, 1038.34646896, 1051.67673646,
       1038.53795043, 1038.27707495, 1033.03321289, 1030.95462159,
       1031.89026707, 1031.44903975, 1034.097271  , 1030.4508555 ,
       1028.15491562, 1031.2974087 , 1014.28252376, 1017.33886067,
       1017.33672157, 1023.64694009, 1016.03841011, 1023.54428307,
       1024.66947841, 1022.23629976, 1025.12708187, 1019.43455256,
       1023.73285401, 1020.08966092, 1018.37799227, 1023.18936334,
       1021.0888479 , 1023.34639897, 1019.64731663, 1011.93100999,
       1021.32354913, 1019.52296526, 1016.59543926, 1014.80747

In [19]:
np.load('/home/jongchan/SDIRL/results/TD3_Hopper-v2_0_exp1_261_09.npy')

array([ 18.0233928 ,  18.0233928 ,  18.0233928 ,  18.0233928 ,
        18.0233928 ,  18.0233928 , 316.48258085, 432.97233565])

In [13]:
np.load('/home/jongchan/SDIRL/results/TD3_Hopper-v2_0.npy')

array([  18.0233928 ,   18.0233928 ,   18.0233928 ,   18.0233928 ,
         18.0233928 ,   18.0233928 ,  170.85664628,  194.16745452,
        201.71691646,  235.74145148,  250.8482574 ,  305.07277414,
        260.72960045,  256.28186206,  261.26954881,  491.87389736,
        255.05331161,  424.76670175,  429.99709579,  247.08666513,
        392.12367646,  235.54533877,  459.09663106,  381.72176027,
        984.62598272, 1173.31965041, 1407.47978492, 1285.5883431 ,
       1281.04590018, 2516.32492572,  844.08222545, 1896.05592446,
       1453.28109067, 1316.48485173, 1786.0406968 ,  554.73262766,
       2047.60290661, 2805.31045345,  326.48168479,  890.54158647,
       1062.17672982, 1437.94185595, 1301.86324354, 2931.684054  ,
       2768.00410392, 3112.88208174,  519.21959812,  308.41978597,
       2022.08769348, 3100.31332673, 3287.16931897, 3133.31692679,
       2496.0369512 , 2860.7358756 , 3214.20382602, 3012.47450908,
       1930.44080013, 1843.24383824, 2868.39919998, 3365.02061